#!/bin/bash

g++ bayesMLR.cpp -o mlr.o -O2 -I $ARMA_HOME -DARMA_DONT_USE_WRAPPER -L$OPENBLAS_HOME -lopenblas -llapack -lgfortran -Wall -fopenmp

#g++ bayesMLR.cpp -o mlr -O2 -I $ARMA_HOME -DARMA_DONT_USE_WRAPPER -lblas -llapack -lgfortran -Wall
#g++ bayesMLR.cpp -o mlr -O2 -I /data/arthurll/armadillo/include -DARMA_DONT_USE_WRAPPER -lblas -llapack -lgfortran 

